# Generated by Django 4.2.16 on 2024-12-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usabilitytestingproject", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_number", models.CharField(max_length=50)),
                ("task_name", models.CharField(max_length=255)),
                ("participant_name", models.CharField(max_length=255)),
            ],
        ),
    ]
